name: Spotify Script that saves albums to your library

on:
  push:
    branches:
      - main

jobs:
  run_index_js:
    runs-on: ubuntu-latest

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Make build
        run: npm run build

      - name: Run dist/index.js
        run: node dist/index.js

      - name: Commit and push log file if it exists
        if: ${{ success() && steps.run_index_js.outputs.check_created == 'true' }}
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add check.txt
          git commit -m "Add log of failed albums"
          git push origin HEAD:logs
